### ISSUE TITLE
Use local cache for `yarn` commands

### ISSUE THREAD

**Issue by corradio** [tmrowco/brick#17]

**Comment by madsnedergaard** [comment]
Additional info from @corradio:

> The cache location varies depending on the node image used (some platforms put the yarn cache different places), but maybe we could maintain a mapping between the image name and cache location.

---	

> I noticed brick was a bit slow during the `prepare` stage when using `yarn`.
This is due to the fact that any change to the package.json or yarn.lock will cause `yarn` to run from scratch (it has to re-download all packages).
Turns out the yarn cache can be cached using this mount command:
>
> ![image](https://user-images.githubusercontent.com/3296643/75247349-02cd9e80-57d2-11ea-98f3-d994e5eef22f.png)
>
> It will make sure to avoid re-downloading packages that are already in the cache. It speeds up quite a lot the build in cases where one adds just a single package!
