### ISSUE TITLE
Doesn't always use previous build cache

### ISSUE THREAD

**Issue by corradio** [tmrowco/brick#24]
Steps to reproduce:
- `brick build`
- do a new commit
- `brick build`
- `git revert` that commit
- `brick build`
Expected:
The first `brick build` should have produced a cache entry, and thus the last `brick build` (after reverting) should re-use that cache and cause a no-op

**Comment by skovhus** [comment]
What happens here is that the second brick build overrides the tag. Docker layers are still cached, so it is rather fast right now.

The only way I see this could be improved is by tagging with branch+commit, which will bloat the docker cache. 

If we solve output collection and image caching on branches (https://github.com/tmrowco/brick/pull/57), then I believe Brick should be fast enough.

I'm closing this for now, please reopen if you disagree.
