### ISSUE TITLE
Make --skip-previous-steps work with recursive flag!

### ISSUE THREAD

**Issue by madsnedergaard** [tmrowco/brick#33]
Hey, I just realised that the --skip-previous-steps isn't working with recursive :(

So I guess we have to pass it down to the ctx.invoke() function, but I'm not quite sure what's the best approach for doing that - should I define a new "@click.argument()" for build, test, deploy functions? 

![Screenshot 2020-05-14 at 11 27 29](https://user-images.githubusercontent.com/3296643/81917893-10771100-95d6-11ea-9af1-14ccfad4d555.png)

Any inputs on how to do this, @corradio?

**Comment by corradio** [comment]
Another possibility is to set it globally, just like `verbose`:

![image](https://user-images.githubusercontent.com/1655848/81918488-cb9faa00-95d6-11ea-91b7-4d08333a81dc.png)

It's definitely a hack though..

I tried to look at https://click.palletsprojects.com/en/7.x/api/#click.Context.invoke to see if one could make sure to preserve `ctx.parent` but couldn't see anything obvious.
