### ISSUE TITLE
brick prune is broken

### ISSUE THREAD

**Issue by corradio** [tmrowco/brick#37]
+ brick -r prune
--
372 | 2020-06-09 01:03:09,556 [INFO] Found 35 target(s)..
373 | Traceback (most recent call last):
374 | File "/usr/local/bin/brick", line 11, in <module>
375 | load_entry_point('brick==0.0.1', 'console_scripts', 'brick')()
376 | File "/usr/local/lib/python3.6/dist-packages/brick/__main__.py", line 480, in entrypoint
377 | cli()  # pylint: disable=no-value-for-parameter
378 | File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
379 | return self.main(*args, **kwargs)
380 | File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
381 | rv = self.invoke(ctx)
382 | File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
383 | return _process_result(sub_ctx.command.invoke(sub_ctx))
384 | File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
385 | return ctx.invoke(self.callback, **ctx.params)
386 | File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
387 | return callback(*args, **kwargs)
388 | File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 17, in new_func
389 | return f(get_current_context(), *args, **kwargs)
390 | File "/usr/local/lib/python3.6/dist-packages/brick/__main__.py", line 457, in prune
391 | if check_recursive(ctx, target, prune):
392 | File "/usr/local/lib/python3.6/dist-packages/brick/__main__.py", line 139, in check_recursive
393 | ctx.invoke(fun, target=recursive_target, skip_previous_steps=ctx.parent.params.get('skip_previous_steps'))
394 | File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
395 | return callback(*args, **kwargs)
396 | File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 17, in new_func
397 | return f(get_current_context(), *args, **kwargs)
398 | TypeError: prune() got an unexpected keyword argument 'skip_previous_steps'

cc @madsnedergaard

**Comment by madsnedergaard** [comment]
Fixed in #39
