### ISSUE TITLE
Log whether all steps in a build were cached or not

### ISSUE THREAD

**Issue by madsnedergaard** [tmrowco/brick#43]
This should help users debug caching of build steps.

Maybe comparing the SHA of the image before & after is a good way?

**Comment by madsnedergaard** [comment]
Tried it at `mn/debugging-cache` branch, but it does not seem to the source of our problem...

<img width="1006" alt="Screenshot 2020-07-15 at 15 33 26" src="https://user-images.githubusercontent.com/3296643/87551384-8ec46200-c6b0-11ea-8274-929223dc89ae.png">

**Comment by corradio** [comment]
Seems like we also could merge with https://github.com/tmrowco/brick/issues/10.
Could be great to hide the Building.. / Finished building logs if the build is faster than 10s (would clear a lot of logs no?)
