### ISSUE TITLE
Missing dependency sha1sum

### ISSUE THREAD

**Issue by Kongkille** [tmrowco/brick#49]
Hi!

I just ran the updated brick, and I had an issue with a missing dependency. I did not have sha1sum installed, which led to most brick commands failing. Perhaps we could install this automatically when installing brick, or add it to the README?

This is the line that throws the error
https://github.com/tmrowco/brick/blob/master/brick/lib.py#L89

**Comment by madsnedergaard** [comment]
On it!

**Comment by skovhus** [comment]
Sorry! I didn’t catch this one as my OS X installation is fairly modded. 

I suspect you already solved this issue, but one workaround is `brew install md5sha1sum`. :)
