### ISSUE TITLE
Keep latest tags for branches

### ISSUE THREAD

**Issue by skovhus** [tmrowco/brick#61]
We recently introduced a [change](https://github.com/tmrowco/brick/pull/57/commits/80575aa701ab5ea2aa31f2198c08639c9cc077a1) to not not tag images on non-main branches with "latest". This avoids cache breaking as all branches will not all push the "latest" image.

At least locally we shouldn't do this as the `latest` tag is usually used for local development in Docker compose files.

Ideas:
1) I think most CIs adds a CI=1 environment variable (we could use that)
2) Or be explicit with an additional argument (but might be confusing)

**Comment by corradio** [comment]
Here's an additional proposal:
Right now, it seems like the "latest" tag is always used as cache key.
If the `cache-from` directive supports having multiple cache entries as potential input, then my suggestion would be to use `cache-from <image>:master, cache-from <image>:<current-branch>`, which, in theory, should always either cache from current branch or from master (and never from latest).

Hope it makes sense - else, happy to clarify.

**Comment by skovhus** [comment]
That is a great idea, and it seems to work. But I would leave this out for in a WIP PR now and observe how CI behaves.
